GH - Added decision around inferred relationships (MUST be transmitted)
datafoodconsortium/standard pull request #15
Opened 2024-04-18 07:38 UTC by RaggedStaff

Resolves issue #14.

2024-04-18 08:13 UTC, RachL approved these changes
LGTM!

2024-04-22 11:40 UTC, simonLouvet approved these changes

2024-04-22 12:52 UTC, lecoqlibre requested changes

2024-04-22 13:59 UTC, RaggedStaff commented on appendixes/technical-decisions/data-validity-and-inferences.md
> +* When transmitting data via the DFC standard. All relationships (including any/all inverse links) in the ontology MUST be provided.
Agreed. I've clarified & pushed a change.

2024-04-22 14:22 UTC, lecoqlibre approved these changes
Thanks!

2024-04-22 14:24 UTC, merged