#16 document platforms order states
datafoodconsortium/standard pull request #21
Opened 2024-05-23 11:32 UTC by RaggedStaff

Closes #16 

Initial draft showing Platform Order State mappings. 

Not sure why it's including a bunch of changes that already appear in [master](../tree/master). :confused:

2024-05-27 18:27 UTC, RachL requested changes

2024-05-27 18:27 UTC, RachL commented on technical-specifications/order-states.md
@RaggedStaff before the address state, the order is at the "cart" state in OFN. In fact, as soon as you land on a shop, an order is open for your user. I don't know if we want to follow this state as well?

regarding the DFC class, maybe it's just me but I found it weird to have order states separated from fulfillment / payment states (as fulfillment and payment state only happen on completed orders - do you see what I mean?)

2024-05-27 18:27 UTC, RachL commented on technical-specifications/order-states.md
Regarding payment state, were did you found the OFN ones? 

In the db I see for OFN these payment states:
- paid
- failed
- credit_owed
- balance_due
- requires_authorization
- void

2024-05-27 18:27 UTC, RachL commented on technical-specifications/order-states.md
For shipping states, I see in the db:

- backorder
- canceled
- partial
- pending
- ready
- shipped

2024-06-04 12:38 UTC, sankarom commented
Hi, For order states, this seems good because Socleo has : 

- draft
- pending (payment or other) = held ?
- completed
- retracted (by the customer)
- cancelled (by the seller)

no real payment status for us, either it is payed or it isn't

and i'm not sure what the Fulfilment States correspond to? what does "processed" order mean?
logistical states ? in this case we have :

- in receipt
- received
- in preparation
- prepared
- in delivery
- delivered

2024-06-19 09:05 UTC, RaggedStaff commented on technical-specifications/order-states.md
It was a long time ago, but I think from @mkllnk

2024-06-19 22:16 UTC, mkllnk commented on technical-specifications/order-states.md
Yes, that document lists the OFN states that have been bundled into the DFC states. For example, `pending` and `processing` are important for OFN while processing the payment but that state doesn't have to be communicated to others. So while a payment is processed, the API will still tell you that the payment is `unpaid`.

2024-07-01 10:23 UTC, RachL requested changes
@RaggedStaff we are missing shipment/cancelled as OFN euivalent? Otherwise I think we are good :+1:

2024-07-15 14:10 UTC, RachL approved these changes

2024-07-30 11:48 UTC, lecoqlibre reviewed
OK for me but a little typo is in Order States > Complete. "Order is finalied" should be "Order is finalized" instead (finalized).

2024-08-06 14:53 UTC, lecoqlibre approved these changes

2024-08-12 19:11 UTC, RachL approved these changes

2024-08-13 07:55 UTC, merged